# Generated by Django 4.1.4 on 2023-01-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecords',
            new_name='Access_Records',
        ),
    ]
