# Generated by Django 4.1.4 on 2023-01-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_accessrecords_access_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access_Records',
            new_name='Access_Record',
        ),
    ]
